name: CargarContenedorRegistry
on:
  push:
    tags:
      - "*"

env:
  REGISTRY_NAME: andescontainers
  APP_NAME: sw-angular-nano

jobs:
  job1:
    name: Create Release branch
    runs-on: ubuntu-latest
    steps:
      - name: Set env
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: "${{ env.RELEASE_VERSION }}"

      - name: Obtener Código
        uses: actions/checkout@main

      - name: Conexión Andes Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{env.REGISTRY_NAME}}.azurecr.io
          username: ${{secrets.CEDEXUSER}}
          password: ${{secrets.CEDEXPASSWORD}}

      - run: |
          az login -u ${{secrets.CEDEXUSER}} -p ${{secrets.CEDEXPASSWORD}}
          az acr login -n andescontainers.azurecr.io
          docker build . -t ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.APP_NAME }}:${{ env.RELEASE_VERSION }}
          docker push ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.APP_NAME }}:${{ env.RELEASE_VERSION }}